/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PraktikumOOP;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUI_bahan_bangunan extends javax.swing.JFrame {

    /**
     * Creates new form GUI_bahan_bangunan
     */
    public GUI_bahan_bangunan() {
        initComponents();
        DefaultTableModel dataModel = (DefaultTableModel) Table_Info.getModel();
        int rowCount = dataModel.getRowCount();
        while(rowCount > 0){
            dataModel.removeRow(rowCount - 1);
            rowCount = dataModel.getRowCount();
        }
    }
    public void clear(){
            txtBHN.setText("");
            txtHRG.setText("");
            txtKTN.setText("");
            txtSTN.setText("");
            txtUKR.setText("");
            btnGroup.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radiobtn1 = new javax.swing.JRadioButton();
        radiobtn2 = new javax.swing.JRadioButton();
        radiobtn3 = new javax.swing.JRadioButton();
        radiobtn4 = new javax.swing.JRadioButton();
        radiobtn5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtBHN = new javax.swing.JTextField();
        txtUKR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSTN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHRG = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKTN = new javax.swing.JTextField();
        btnCETAK = new javax.swing.JToggleButton();
        btnCLOSE = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Info = new javax.swing.JTable();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PENJUALAN BAHAN BANGUNAN");

        jLabel2.setText("Jenis bahan Bangunan");

        radiobtn1.setText("Perekat");
        radiobtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn1ActionPerformed(evt);
            }
        });

        radiobtn2.setText("Bangunan");

        radiobtn3.setText("Pelapis");
        radiobtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn3ActionPerformed(evt);
            }
        });

        radiobtn4.setText("Atap");

        radiobtn5.setText("Instalasi");

        jLabel3.setText("Nama Bahan Bangunan");

        txtUKR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUKRActionPerformed(evt);
            }
        });

        jLabel4.setText("Ukuran Bahan");

        jLabel5.setText("Satuan yang dibeli");

        jLabel6.setText("Harga Satuan");

        txtHRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHRGActionPerformed(evt);
            }
        });

        jLabel7.setText("Ketersedian Bahan");

        txtKTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKTNActionPerformed(evt);
            }
        });

        btnCETAK.setText("Cetak");
        btnCETAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCETAKActionPerformed(evt);
            }
        });

        btnCLOSE.setText("Close");
        btnCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLOSEActionPerformed(evt);
            }
        });

        Table_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Jenis", "Nama Bhn", "jmlh Brng", "Harga satuan", "Ready Stok", "Jmlh Harga", "Sisa Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table_Info);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiobtn1)
                                    .addComponent(radiobtn2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBHN)
                                    .addComponent(txtUKR)
                                    .addComponent(txtSTN)
                                    .addComponent(txtHRG)
                                    .addComponent(txtKTN, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiobtn4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radiobtn3)
                                        .addGap(18, 18, 18)
                                        .addComponent(radiobtn5))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCETAK)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_hapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_batal)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCLOSE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radiobtn1)
                    .addComponent(radiobtn3)
                    .addComponent(radiobtn5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtn2)
                    .addComponent(radiobtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtBHN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUKR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtHRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtKTN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCETAK)
                    .addComponent(btnCLOSE)
                    .addComponent(btn_hapus)
                    .addComponent(btn_batal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn1ActionPerformed

    private void radiobtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn3ActionPerformed

    private void txtUKRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUKRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUKRActionPerformed

    private void txtHRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHRGActionPerformed

    private void txtKTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKTNActionPerformed

    private void btnCETAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCETAKActionPerformed
        JOptionPane.showMessageDialog(null, "Data anda Ditambahkan Ke tabel");
        // Mengambil model data dari tabel
        DefaultTableModel dataModel = (DefaultTableModel)
        Table_Info.getModel();
        // Inisialisasi sebuah ArrayList bernama 'list'
        List list = new ArrayList<>();
        // Mengatur tabel untuk membuat kolom dari model secara otomatis
        Table_Info.setAutoCreateColumnsFromModel(true);
        
        CLI_Bahan bhn = new DataPembeli();
        //Polimorfisme Upcasting dari subClass
        DataPembeli stk = (DataPembeli)  bhn;
        //Polimorfisme Downcasting untuk mengembalikan Method ke SuperClass
        
        bhn.dataBahan(txtBHN.getText());
        bhn.dataUkuran(txtUKR.getText());
        bhn.setStok(Integer.parseInt(txtKTN.getText()));
        
        if (radiobtn1.isSelected()){
        bhn.dataJenis(radiobtn1.getText());
         }
        else if(radiobtn2.isSelected()){
            bhn.dataJenis(radiobtn2.getText());
         }
        else if(radiobtn3.isSelected()){
            bhn.dataJenis(radiobtn3.getText());
         }
        else if(radiobtn4.isSelected()){
            bhn.dataJenis(radiobtn4.getText());
         }
        else {
            bhn.dataJenis(radiobtn5.getText());
        }
        try {
            String totalsatuan = txtSTN.getText();
            if (totalsatuan.isEmpty() || totalsatuan.equals("0")){
                JOptionPane.showMessageDialog(null, "Satuan tidak boleh kosong atau bernilai 0", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Menghentikan eksekusi lebih lanjut karena data tidak valid.
            }
            bhn.setSatuan(Integer.parseInt(txtSTN.getText()));
            bhn.dataHarga(Integer.parseInt(txtHRG.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Masukkan angka yang valid untuk Satuan dan Harga", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        list.add(bhn.cetakJenis());
        list.add(bhn.cetakBahan());
        list.add(bhn.getSatuan()+ bhn.cetakUkuran());
        list.add(bhn.cetakHarga());
        list.add(bhn.getStok());
        list.add(bhn.HitTotal());
        list.add(stk.CekStok());
        
         // Menambahkan baris baru ke model tabel menggunakan data dari ArrayList 'list'
        dataModel.addRow(list.toArray());
        // Memanggil fungsi 'clear' untuk membersihkan nilai dari komponen
        clear();
    }//GEN-LAST:event_btnCETAKActionPerformed

    private void btnCLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLOSEActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCLOSEActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) Table_Info.getModel();
        int rowCount = dataModel.getRowCount();
        while(rowCount > 0){
            dataModel.removeRow(rowCount - 1);
            rowCount = dataModel.getRowCount();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_bahan_bangunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_bahan_bangunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_bahan_bangunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_bahan_bangunan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_bahan_bangunan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Info;
    private javax.swing.JToggleButton btnCETAK;
    private javax.swing.JToggleButton btnCLOSE;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton radiobtn1;
    private javax.swing.JRadioButton radiobtn2;
    private javax.swing.JRadioButton radiobtn3;
    private javax.swing.JRadioButton radiobtn4;
    private javax.swing.JRadioButton radiobtn5;
    private javax.swing.JTextField txtBHN;
    private javax.swing.JTextField txtHRG;
    private javax.swing.JTextField txtKTN;
    private javax.swing.JTextField txtSTN;
    private javax.swing.JTextField txtUKR;
    // End of variables declaration//GEN-END:variables
}
